import Head from 'next/head'
import Image from 'next/image'

const imgURL = 'https://scontent-scl2-1.xx.fbcdn.net/v/t1.6435-1/c0.48.200.200a/p200x200/154689627_957227618146549_1138984391772154048_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=7206a8&_nc_eui2=AeEymTb7nAYIHIORfrh2XHalkHohFmHPY9WQeiEWYc9j1SROJ7fVL_uDVnTuGu5ZRNKN1jXoylTbBGYMU3z9AERB&_nc_ohc=DDriUpXhsGYAX-oNEQ_&_nc_ht=scontent-scl2-1.xx&tp=27&oh=b46fd72861b777d9adab7aea5622294d&oe=60E6D59E'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hans Piña | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
          <h1>Home</h1>
          <h1>About Me</h1>
          <h1>Experience</h1>
          <h1>Work</h1>
          <h1>Contact</h1>
          <footer>
              <div>Designed & Built by Hans Piña, @hansfpc.</div>
          </footer>
      </div>
    </div>
  )
}
