import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const imgURL = 'https://scontent-scl2-1.xx.fbcdn.net/v/t1.6435-1/c0.48.200.200a/p200x200/154689627_957227618146549_1138984391772154048_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=7206a8&_nc_eui2=AeEymTb7nAYIHIORfrh2XHalkHohFmHPY9WQeiEWYc9j1SROJ7fVL_uDVnTuGu5ZRNKN1jXoylTbBGYMU3z9AERB&_nc_ohc=DDriUpXhsGYAX-oNEQ_&_nc_ht=scontent-scl2-1.xx&tp=27&oh=b46fd72861b777d9adab7aea5622294d&oe=60E6D59E'

export default function Home() {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Hans Piña | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
          <header className={styles.headerContainer}>
             <div>LOGO</div>
              <div className={styles.menuContainer}>
                  <ul className={styles.menuList}>
                      <li className={styles.menuItem}>About</li>
                      <li className={styles.menuItem}>Experience</li>
                      <li className={styles.menuItem}>Work</li>
                      <li className={styles.menuItem}>Contact</li>
                  </ul>
                  <a href="#" className={styles.resumeButton}>Resume</a>
              </div>
          </header>
          <div>
              <h1>Hi, my name is</h1>
              <h2>Hans Piña</h2>
              <h3>I build things for the www.</h3>
              <p>I&#39;m a software engineer based on Santiago de Chile who specializes in building and deliverying great digital experiences. Currently, I&#39;m an engineer at Reign focused on building accessible, human-centered products.</p>
          </div>
          <h1>About Me</h1>
          <h1>Experience</h1>
          <h1>Work</h1>
          <h1>Contact</h1>
          <footer className={styles.footerContainer}>
              <div>Designed & Built by Hans Piña, @hansfpc.</div>
          </footer>
      </div>
    </div>
  )
}
